---
title: "stad80_final"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

## Linear Decomposition
```{r}
curve(1*x-0.3,from=0,to=1, col="black",ylab="y", xlim=c(0,1),ylim=c(0,0.9))
abline(h=0.5, col="purple")
points(c(.5,.5),c(.5,0.8))
legend(0,0.8, legend=c("Fitted Line", "E(Y|X)"),
       col=c("black", "purple"), lty=1)
lines(c(.5,.5),c(0.2,0.5), col="blue")
lines(c(.5,.5),c(0.5,0.8), col="red")
text(.35,.325,label = "Approximation Error", col="blue")
text(.44,.7,label = "Noise",col="red")
```

## Non-linear Decomposition
```{r}
set.seed(1)
curve(x^2,from=1,to=2, xlab="x",ylab="y", col="purple")
abline(0,1)
points(c(1.5,1.5),c(3.5,1.5^2))
legend(1,3.5, legend=c("Fitted Line", "E(Y|X)"),
       col=c("black", "purple"), lty=1)
lines(c(1.5,1.5),c(1.5,1.5^2), col="blue")
lines(c(1.5,1.5),c(1.5^2,3.5), col="red")
text(1.65,2,label = "Approximation Error", col="blue")
text(1.45,3,label = "Noise",col="red")
```


## Linear Regression: Fixed Design

```{r}
#Fixed linear regression 
set.seed(1)
Explanatory <- seq(-2,2,length.out=100)
Response <- Explanatory + rnorm(length(Explanatory))
model <- lm(Response~Explanatory)
model_summary <- model %>% broom::tidy() %>% kable()

plot(Response~Explanatory)
abline(model)

plot(model,which = 2)
```




## Linear Regression: Random Design
```{r}
set.seed(1)
Explanatory <- rnorm(100)
Response <- Explanatory + rnorm(length(Explanatory))
model <- lm(Response~Explanatory)
model_summary <- model %>% broom::tidy() %>% kable()

plot(Response~Explanatory)
abline(model)

plot(model, which=2)
```



## Monte Carlo
```{r}
set.seed(1)
N <- 1000
X <- seq(-3,3,length.out=100)
beta_fixed <- vector()
for (i in 1:N){
  y <- X +rnorm(100)
  model <- lm(y~X)
  beta_fixed[i] <- model$coefficients[2]
}
beta_random <- vector()
for (i in 1:N){
  X <- rnorm(100)
  y <- X+rnorm(100)
  model <- lm(y~X)
  beta_random[i] <- model$coefficients[2]
}

par(mfrow=c(1,2))
plot(density(beta_fixed),cex.main=1, main="Distribution of Estimated \n Coefficients - Fixed X", xlab = "N=1000")
plot(density(beta_random),cex.main=1, main="Distribution of Estimated \n Coefficients - Random X", xlab = "N=1000")
```






